<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'a4d38248d2b4423eb01a1a3e2f9fa22f943f0759',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'a4d38248d2b4423eb01a1a3e2f9fa22f943f0759',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v5.2.28',
            'version' => '5.2.28.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'acba50393dd03da69a50226c139722af8b153b11',
            'dev_requirement' => false,
        ),
        'smarty/smarty' => array(
            'pretty_version' => 'v3.1.45',
            'version' => '3.1.45.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty',
            'aliases' => array(),
            'reference' => 'a2713ab89e6d773bc4819f11857af7f6b2e353a9',
            'dev_requirement' => false,
        ),
    ),
);
